version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  jobs:
    pre_build:
     - sphinx-apidoc -e -T --templatedir docs/_templates/apidoc -o docs/apidoc src/tabe

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# formats:
#   - pdf
#   - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
